services:

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    container_name: codeigniter55100_node
    restart: unless-stopped
    environment:
      WS_PORT: 3000
    networks:
      - codeigniter55100_net
    depends_on:
      - php
