DROP TABLE IF EXISTS `candidato_2024_RJ`;

CREATE TABLE `candidato_2024_RJ` (
	`id` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`NR_MUNICIPIO` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`NM_MUNICIPIO` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`NR_CANDIDATO` VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`NM_CANDIDATO` VARCHAR(150) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`SG_PARTIDO` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`NM_PARTIDO` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`QT_VOTOS_NOMINAIS_VALIDOS` BIGINT UNSIGNED NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COMMENT='Votos nominais válidos por candidato/município — Eleições 2024 RJ'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB;
