DROP TABLE IF EXISTS `partidos_2024_RJ`;

CREATE TABLE `partidos_2024_RJ` (
    `ID`         INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `SG_PARTIDO` VARCHAR(50)  NOT NULL,
    `NM_PARTIDO` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`ID`)
);
