UPDATE votacao_secao_2022_RJ
SET SG_PARTIDO = CASE
        LEFT(NR_CANDIDATO, 2)
        WHEN '10' THEN 'REPUBLICANOS'
        WHEN '11' THEN 'PP'
        WHEN '12' THEN 'PDT'
        WHEN '13' THEN 'PT'
        WHEN '14' THEN 'PTB'
        WHEN '15' THEN 'MDB'
        WHEN '16' THEN 'DC'
        WHEN '18' THEN 'REDE'
        WHEN '19' THEN 'PODE' -- VERIFICAR
        WHEN '20' THEN 'PSC' -- VERIFICAR
        WHEN '21' THEN 'PROS'
        WHEN '22' THEN 'PL'
        WHEN '23' THEN 'CIDADANIA'
        WHEN '27' THEN 'DC' -- VERIFICAR (pode ser diferente do 16)
        WHEN '28' THEN 'PRTB'
        WHEN '30' THEN 'NOVO'
        WHEN '33' THEN 'PMN'
        WHEN '35' THEN 'PMB'
        WHEN '36' THEN 'AGIR'
        WHEN '40' THEN 'PSB'
        WHEN '43' THEN 'PV'
        WHEN '44' THEN 'UNIÃO'
        WHEN '45' THEN 'PSDB'
        WHEN '50' THEN 'PSOL'
        WHEN '51' THEN 'PATRIOTA'
        WHEN '55' THEN 'PSD'
        WHEN '65' THEN 'PCdoB'
        WHEN '70' THEN 'AVANTE'
        WHEN '77' THEN 'SOLIDARIEDADE'
        WHEN '80' THEN 'UP'
        ELSE NULL
    END,
    NM_PARTIDO = CASE
        LEFT(NR_CANDIDATO, 2)
        WHEN '10' THEN 'REPUBLICANOS'
        WHEN '11' THEN 'PROGRESSISTAS'
        WHEN '12' THEN 'PDT'
        WHEN '13' THEN 'PARTIDO DOS TRABALHADORES'
        WHEN '14' THEN 'PARTIDO TRABALHISTA BRASILEIRO'
        WHEN '15' THEN 'MOVIMENTO DEMOCRÁTICO BRASILEIRO'
        WHEN '16' THEN 'DEMOCRACIA CRISTÃ'
        WHEN '18' THEN 'REDE SUSTENTABILIDADE'
        WHEN '19' THEN 'PODEMOS' -- VERIFICAR
        WHEN '20' THEN 'PARTIDO SOCIAL CRISTÃO' -- VERIFICAR
        WHEN '21' THEN 'PARTIDO REPUBLICANO DA ORDEM SOCIAL'
        WHEN '22' THEN 'PARTIDO LIBERAL'
        WHEN '23' THEN 'CIDADANIA'
        WHEN '27' THEN 'DEMOCRACIA CRISTÃ' -- VERIFICAR
        WHEN '28' THEN 'PARTIDO RENOVADOR TRABALHISTA BRASILEIRO'
        WHEN '30' THEN 'NOVO'
        WHEN '33' THEN 'PARTIDO DA MOBILIZAÇÃO NACIONAL'
        WHEN '35' THEN 'PARTIDO DA MULHER BRASILEIRA'
        WHEN '36' THEN 'AGIR'
        WHEN '40' THEN 'PARTIDO SOCIALISTA BRASILEIRO'
        WHEN '43' THEN 'PARTIDO VERDE'
        WHEN '44' THEN 'UNIÃO BRASIL'
        WHEN '45' THEN 'PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA'
        WHEN '50' THEN 'PARTIDO SOCIALISMO E LIBERDADE'
        WHEN '51' THEN 'PATRIOTA'
        WHEN '55' THEN 'PARTIDO SOCIAL DEMOCRÁTICO'
        WHEN '65' THEN 'PARTIDO COMUNISTA DO BRASIL'
        WHEN '70' THEN 'AVANTE'
        WHEN '77' THEN 'SOLIDARIEDADE'
        WHEN '80' THEN 'UNIDADE POPULAR'
        ELSE NULL
    END
WHERE SG_PARTIDO IS NULL;