UPDATE municipio_ibge_tse SET cd_tse = '58017' WHERE nm_cidade = 'Angra dos Reis';
UPDATE municipio_ibge_tse SET cd_tse = '58181' WHERE nm_cidade = 'Aperibé';
UPDATE municipio_ibge_tse SET cd_tse = '58033' WHERE nm_cidade = 'Araruama';
UPDATE municipio_ibge_tse SET cd_tse = '58220' WHERE nm_cidade = 'Areal';
UPDATE municipio_ibge_tse SET cd_tse = '58408' WHERE nm_cidade = 'Armação dos Búzios';
UPDATE municipio_ibge_tse SET cd_tse = '59277' WHERE nm_cidade = 'Arraial do Cabo';
UPDATE municipio_ibge_tse SET cd_tse = '58050' WHERE nm_cidade = 'Barra do Piraí';
UPDATE municipio_ibge_tse SET cd_tse = '58076' WHERE nm_cidade = 'Barra Mansa';
UPDATE municipio_ibge_tse SET cd_tse = '58041' WHERE nm_cidade = 'Belford Roxo';
UPDATE municipio_ibge_tse SET cd_tse = '58092' WHERE nm_cidade = 'Bom Jardim';
UPDATE municipio_ibge_tse SET cd_tse = '58114' WHERE nm_cidade = 'Bom Jesus do Itabapoana';
UPDATE municipio_ibge_tse SET cd_tse = '58130' WHERE nm_cidade = 'Cabo Frio';
UPDATE municipio_ibge_tse SET cd_tse = '58157' WHERE nm_cidade = 'Cachoeiras de Macacu';
UPDATE municipio_ibge_tse SET cd_tse = '58173' WHERE nm_cidade = 'Cambuci';
UPDATE municipio_ibge_tse SET cd_tse = '58190' WHERE nm_cidade = 'Campos dos Goytacazes';
UPDATE municipio_ibge_tse SET cd_tse = '58211' WHERE nm_cidade = 'Cantagalo';
UPDATE municipio_ibge_tse SET cd_tse = '58300' WHERE nm_cidade = 'Carapebus';
UPDATE municipio_ibge_tse SET cd_tse = '58068' WHERE nm_cidade = 'Cardoso Moreira';
UPDATE municipio_ibge_tse SET cd_tse = '58238' WHERE nm_cidade = 'Carmo';
UPDATE municipio_ibge_tse SET cd_tse = '58254' WHERE nm_cidade = 'Casimiro de Abreu';
UPDATE municipio_ibge_tse SET cd_tse = '58165' WHERE nm_cidade = 'Comendador Levy Gasparian';
UPDATE municipio_ibge_tse SET cd_tse = '58270' WHERE nm_cidade = 'Conceição de Macabu';
UPDATE municipio_ibge_tse SET cd_tse = '58297' WHERE nm_cidade = 'Cordeiro';
UPDATE municipio_ibge_tse SET cd_tse = '58319' WHERE nm_cidade = 'Duas Barras';
UPDATE municipio_ibge_tse SET cd_tse = '58335' WHERE nm_cidade = 'Duque de Caxias';
UPDATE municipio_ibge_tse SET cd_tse = '58351' WHERE nm_cidade = 'Engenheiro Paulo de Frontin';
UPDATE municipio_ibge_tse SET cd_tse = '58106' WHERE nm_cidade = 'Guapimirim';
UPDATE municipio_ibge_tse SET cd_tse = '58262' WHERE nm_cidade = 'Iguaba Grande';
UPDATE municipio_ibge_tse SET cd_tse = '58378' WHERE nm_cidade = 'Itaboraí';
UPDATE municipio_ibge_tse SET cd_tse = '58394' WHERE nm_cidade = 'Itaguaí';
UPDATE municipio_ibge_tse SET cd_tse = '59293' WHERE nm_cidade = 'Italva';
UPDATE municipio_ibge_tse SET cd_tse = '58416' WHERE nm_cidade = 'Itaocara';
UPDATE municipio_ibge_tse SET cd_tse = '58432' WHERE nm_cidade = 'Itaperuna';
UPDATE municipio_ibge_tse SET cd_tse = '58440' WHERE nm_cidade = 'Itatiaia';
UPDATE municipio_ibge_tse SET cd_tse = '58149' WHERE nm_cidade = 'Japeri';
UPDATE municipio_ibge_tse SET cd_tse = '58459' WHERE nm_cidade = 'Laje do Muriaé';
UPDATE municipio_ibge_tse SET cd_tse = '58475' WHERE nm_cidade = 'Macaé';
UPDATE municipio_ibge_tse SET cd_tse = '58386' WHERE nm_cidade = 'Macuco';
UPDATE municipio_ibge_tse SET cd_tse = '58491' WHERE nm_cidade = 'Magé';
UPDATE municipio_ibge_tse SET cd_tse = '58513' WHERE nm_cidade = 'Mangaratiba';
UPDATE municipio_ibge_tse SET cd_tse = '58530' WHERE nm_cidade = 'Maricá';
UPDATE municipio_ibge_tse SET cd_tse = '58556' WHERE nm_cidade = 'Mendes';
UPDATE municipio_ibge_tse SET cd_tse = '58467' WHERE nm_cidade = 'Mesquita';
UPDATE municipio_ibge_tse SET cd_tse = '58572' WHERE nm_cidade = 'Miguel Pereira';
UPDATE municipio_ibge_tse SET cd_tse = '58599' WHERE nm_cidade = 'Miracema';
UPDATE municipio_ibge_tse SET cd_tse = '58610' WHERE nm_cidade = 'Natividade';
UPDATE municipio_ibge_tse SET cd_tse = '58637' WHERE nm_cidade = 'Nilópolis';
UPDATE municipio_ibge_tse SET cd_tse = '58653' WHERE nm_cidade = 'Niterói';
UPDATE municipio_ibge_tse SET cd_tse = '58670' WHERE nm_cidade = 'Nova Friburgo';
UPDATE municipio_ibge_tse SET cd_tse = '58696' WHERE nm_cidade = 'Nova Iguaçu';
UPDATE municipio_ibge_tse SET cd_tse = '58718' WHERE nm_cidade = 'Paracambi';
UPDATE municipio_ibge_tse SET cd_tse = '58734' WHERE nm_cidade = 'Paraíba do Sul';
UPDATE municipio_ibge_tse SET cd_tse = '58750' WHERE nm_cidade = 'Paraty';
UPDATE municipio_ibge_tse SET cd_tse = '59315' WHERE nm_cidade = 'Paty do Alferes';
UPDATE municipio_ibge_tse SET cd_tse = '58777' WHERE nm_cidade = 'Petrópolis';
UPDATE municipio_ibge_tse SET cd_tse = '58246' WHERE nm_cidade = 'Pinheiral';
UPDATE municipio_ibge_tse SET cd_tse = '58793' WHERE nm_cidade = 'Piraí';
UPDATE municipio_ibge_tse SET cd_tse = '58815' WHERE nm_cidade = 'Porciúncula';
UPDATE municipio_ibge_tse SET cd_tse = '58327' WHERE nm_cidade = 'Porto Real';
UPDATE municipio_ibge_tse SET cd_tse = '58025' WHERE nm_cidade = 'Quatis';
UPDATE municipio_ibge_tse SET cd_tse = '58122' WHERE nm_cidade = 'Queimados';
UPDATE municipio_ibge_tse SET cd_tse = '58009' WHERE nm_cidade = 'Quissamã';
UPDATE municipio_ibge_tse SET cd_tse = '58831' WHERE nm_cidade = 'Resende';
UPDATE municipio_ibge_tse SET cd_tse = '58858' WHERE nm_cidade = 'Rio Bonito';
UPDATE municipio_ibge_tse SET cd_tse = '58874' WHERE nm_cidade = 'Rio Claro';
UPDATE municipio_ibge_tse SET cd_tse = '58890' WHERE nm_cidade = 'Rio das Flores';
UPDATE municipio_ibge_tse SET cd_tse = '58203' WHERE nm_cidade = 'Rio das Ostras';
UPDATE municipio_ibge_tse SET cd_tse = '60011' WHERE nm_cidade = 'Rio de Janeiro';
UPDATE municipio_ibge_tse SET cd_tse = '58912' WHERE nm_cidade = 'Santa Maria Madalena';
UPDATE municipio_ibge_tse SET cd_tse = '58939' WHERE nm_cidade = 'Santo Antônio de Pádua';
UPDATE municipio_ibge_tse SET cd_tse = '58955' WHERE nm_cidade = 'São Fidélis';
UPDATE municipio_ibge_tse SET cd_tse = '58289' WHERE nm_cidade = 'São Francisco de Itabapoana';
UPDATE municipio_ibge_tse SET cd_tse = '58971' WHERE nm_cidade = 'São Gonçalo';
UPDATE municipio_ibge_tse SET cd_tse = '58998' WHERE nm_cidade = 'São João da Barra';
UPDATE municipio_ibge_tse SET cd_tse = '59013' WHERE nm_cidade = 'São João de Meriti';
UPDATE municipio_ibge_tse SET cd_tse = '58343' WHERE nm_cidade = 'São José de Ubá';
UPDATE municipio_ibge_tse SET cd_tse = '59331' WHERE nm_cidade = 'São José do Vale do Rio Preto';
UPDATE municipio_ibge_tse SET cd_tse = '59030' WHERE nm_cidade = 'São Pedro da Aldeia';
UPDATE municipio_ibge_tse SET cd_tse = '59056' WHERE nm_cidade = 'São Sebastião do Alto';
UPDATE municipio_ibge_tse SET cd_tse = '59072' WHERE nm_cidade = 'Sapucaia';
UPDATE municipio_ibge_tse SET cd_tse = '59099' WHERE nm_cidade = 'Saquarema';
UPDATE municipio_ibge_tse SET cd_tse = '58424' WHERE nm_cidade = 'Seropédica';
UPDATE municipio_ibge_tse SET cd_tse = '59110' WHERE nm_cidade = 'Silva Jardim';
UPDATE municipio_ibge_tse SET cd_tse = '59137' WHERE nm_cidade = 'Sumidouro';
UPDATE municipio_ibge_tse SET cd_tse = '58360' WHERE nm_cidade = 'Tanguá';
UPDATE municipio_ibge_tse SET cd_tse = '59153' WHERE nm_cidade = 'Teresópolis';
UPDATE municipio_ibge_tse SET cd_tse = '59170' WHERE nm_cidade = 'Trajano de Moraes';
UPDATE municipio_ibge_tse SET cd_tse = '59196' WHERE nm_cidade = 'Três Rios';
UPDATE municipio_ibge_tse SET cd_tse = '59218' WHERE nm_cidade = 'Valença';
UPDATE municipio_ibge_tse SET cd_tse = '58084' WHERE nm_cidade = 'Varre-Sai';
UPDATE municipio_ibge_tse SET cd_tse = '59234' WHERE nm_cidade = 'Vassouras';
UPDATE municipio_ibge_tse SET cd_tse = '59250' WHERE nm_cidade = 'Volta Redonda';