CREATE OR REPLACE VIEW view_votos_municipio_2024_RJ AS
SELECT
    ROW_NUMBER() OVER (
        ORDER BY NM_MUNICIPIO, SUM(CAST(QT_VOTOS AS UNSIGNED)) DESC
    ) AS ID,
    CD_MUNICIPIO,
    NM_MUNICIPIO,
    DS_CARGO,
    CD_CARGO,
    SG_PARTIDO,
    NM_PARTIDO,
    NR_VOTAVEL,
    NM_VOTAVEL,
    SUM(CAST(QT_VOTOS AS UNSIGNED)) AS QT_VOTOS
FROM votacao_secao_2024_RJ
GROUP BY
    CD_MUNICIPIO,
    NM_MUNICIPIO,
    DS_CARGO,
    CD_CARGO,
    SG_PARTIDO,
    NM_PARTIDO,
    NR_VOTAVEL,
    NM_VOTAVEL
ORDER BY
    NM_MUNICIPIO,
    QT_VOTOS DESC;