CREATE OR REPLACE VIEW `view_votos_municipio_2022_RJ` AS
SELECT CONCAT(
        `CD_MUNICIPIO`, '.', `NR_CANDIDATO`, '.', `DS_CARGO`
    ) AS `ID`,
    `CD_MUNICIPIO`,
    `NM_MUNICIPIO`,
    `DS_CARGO`,
    `SG_PARTIDO`,
    `NM_PARTIDO`,
    `NR_CANDIDATO`,
    `NM_CANDIDATO`,
    `NM_SOCIAL_CANDIDATO`,
    SUM(CAST(`QT_VOTOS_NOMINAIS` AS UNSIGNED)) AS `QT_VOTOS_NOMINAIS`,
    `DS_SIT_TOT_TURNO`
FROM `votacao_candidato_munzona_2022_RJ`
GROUP BY `CD_MUNICIPIO`,
    `NM_MUNICIPIO`,
    `DS_CARGO`,
    `SG_PARTIDO`,
    `NM_PARTIDO`,
    `NR_CANDIDATO`,
    `NM_CANDIDATO`,
    `NM_SOCIAL_CANDIDATO`,
    `DS_SIT_TOT_TURNO`;
