CREATE OR REPLACE VIEW `view_votos_municipio_2022` AS
SELECT ROW_NUMBER() OVER (
        ORDER BY `NM_MUNICIPIO`,
            SUM(CAST(`QT_VOTOS_NOMINAIS` AS UNSIGNED)) DESC
    ) AS `ID`,
    `CD_MUNICIPIO`,
    `NM_MUNICIPIO`,
    `DS_CARGO`,
    `NR_CANDIDATO`,
    `NM_CANDIDATO`,
    `NM_SOCIAL_CANDIDATO`,
    SUM(CAST(`QT_VOTOS_NOMINAIS` AS UNSIGNED)) AS `QT_VOTOS_NOMINAIS`,
    `DS_SIT_TOT_TURNO`
FROM `votacao_candidato_munzona_2022_RJ`
GROUP BY `NM_MUNICIPIO`,
    `DS_CARGO`,
    `NR_CANDIDATO`,
    `NM_CANDIDATO`,
    `NM_SOCIAL_CANDIDATO`,
    `DS_SIT_TOT_TURNO`
    ORDER BY NM_MUNICIPIO ASC, QT_VOTOS_NOMINAIS DESC;