CREATE OR REPLACE VIEW view_votacao_candidato_munzona_2024_RJ_group AS
SELECT
    CONCAT('2024', `NR_VOTAVEL`, `CD_MUNICIPIO`) AS `ID`,
    CD_MUNICIPIO,
    NM_MUNICIPIO,
    DS_CARGO,
    SG_PARTIDO,
    NM_PARTIDO,
    NR_VOTAVEL,
    NM_VOTAVEL,
    SUM(CAST(QT_VOTOS AS UNSIGNED)) AS QT_VOTOS
FROM votacao_secao_2024_RJ
GROUP BY
    CD_MUNICIPIO,
    NM_MUNICIPIO,
    DS_CARGO,
    SG_PARTIDO,
    NM_PARTIDO,
    NR_VOTAVEL,
    NM_VOTAVEL
ORDER BY
    QT_VOTOS DESC;