CREATE OR REPLACE VIEW view_candidato_2022_RJ AS
SELECT CONCAT(
        ANO_ELEICAO,
        '.',
        CD_MUNICIPIO,
        '.',
        NR_CANDIDATO
    ) AS ID,
    CD_MUNICIPIO,
    NM_MUNICIPIO,
    NR_CANDIDATO,
    NM_CANDIDATO,
    SG_PARTIDO,
    NM_PARTIDO,
    SUM(CAST(QT_VOTOS_NOMINAIS_VALIDOS AS UNSIGNED)) AS QT_VOTOS_NOMINAIS_VALIDOS
FROM votacao_candidato_munzona_2022_RJ
GROUP BY ANO_ELEICAO,
    CD_MUNICIPIO,
    NM_MUNICIPIO,
    NR_CANDIDATO,
    NM_CANDIDATO,
    SG_PARTIDO,
    NM_PARTIDO
ORDER BY NM_MUNICIPIO ASC,
NM_CANDIDATO ASC;