CREATE OR REPLACE VIEW `vw_votos_candidato_2022_RJ` AS
SELECT ROW_NUMBER() OVER (
        ORDER BY SUM(CAST(`QT_VOTOS_NOMINAIS` AS UNSIGNED)) DESC
    ) AS `ID`,
    `DS_CARGO`,
    `NR_CANDIDATO`,
    `NM_CANDIDATO`,
    `NM_SOCIAL_CANDIDATO`,
    SUM(CAST(`QT_VOTOS_NOMINAIS` AS UNSIGNED)) AS `QT_VOTOS_NOMINAIS`,
    `DS_SIT_TOT_TURNO`
FROM `votacao_candidato_munzona_2022_RJ`
GROUP BY `DS_CARGO`,
    `NR_CANDIDATO`,
    `NM_CANDIDATO`,
    `NM_SOCIAL_CANDIDATO`,
    `DS_SIT_TOT_TURNO`;