CREATE OR REPLACE VIEW view_candidato_2024_RJ AS
SELECT CONCAT(
        ANO_ELEICAO, '.', CD_MUNICIPIO, '.', NR_VOTAVEL, '.', SG_PARTIDO
    ) AS ID,
    CD_MUNICIPIO,
    NM_MUNICIPIO,
    NR_VOTAVEL,
    NM_VOTAVEL,
    SG_PARTIDO,
    NM_PARTIDO,
    SUM(CAST(QT_VOTOS AS UNSIGNED)) AS QT_VOTOS_NOMINAIS_VALIDOS
FROM votacao_secao_2024_RJ
GROUP BY ANO_ELEICAO,
    CD_MUNICIPIO,
    NM_MUNICIPIO,
    NR_VOTAVEL,
    NM_VOTAVEL,
    SG_PARTIDO,
    NM_PARTIDO;
