CREATE OR REPLACE VIEW view_partidos_2024_RJ AS
SELECT
    ANO_ELEICAO,
    SG_PARTIDO,
    NM_PARTIDO
FROM votacao_secao_2024_RJ
WHERE NM_PARTIDO IS NOT NULL
GROUP BY ANO_ELEICAO, SG_PARTIDO, NM_PARTIDO
ORDER BY SG_PARTIDO ASC;